### PR TITLE
Add duetOpen and duetClose events

### PR DESCRIPTION
**Pull request by chardin1**
Add 2 events:

- `duetOpen`
- `duetClose`

These fire when the date picker modal is opened or closed.

### CODE REVIEW

**Comment by WickyNilliams** [comment]
This looks good, thanks!

Small request: can you please remove the changes to package.json version? And then rebase/squash all commits down to a single commit.

**Comment by chardin1** [comment]
Whoops, sorry. First time doing a PR and I thought I needed to run the `npm version minor` command via the documentation. Should be fixed now.

**Comment by chardin1** [comment]
Any idea when this might make it into a new release?

**Comment by WickyNilliams** [comment]
That's mostly in the docs so that I don't forget haha. Appreciate you taking the time for your first PR!

I'll get this merged and released next week

**Comment by WickyNilliams** [comment]
Thanks again!

**Comment by WickyNilliams** [comment]
Released in `v1.3.0`

**Pull request merged**
