### PR TITLE
Add --duet-color-border variable for border color

### LINKED ISSUE #41: Expand CSS variables
**Is your feature request related to a problem? Please describe.**

Some of the colors are re-used and may/will lead to difficulties when customising inputs. Specifically, borders:

```css
.duet-date__input {
    border: 1px solid var(--duet-color-text);
    border-radius: var(--duet-radius);
    color: var(--duet-color-text);
}
```

**Describe the solution you'd like**

Add a new variable, `--duet-color-border`. To maintain backards compatibility, it can fall back:

```
border: 1px solid var(--duet-color-border, var(--duet-border-text))
```

**Additional context**

See why here (duetds among material ui fields)

Screenshot 2020-10-30 at 14 43 22

----

By the way, the picker is amazing 🎉

### PR DESCRIPTION
**Pull request by dmitriid**
Fixes #41

I kept it backwards compatible by defaulting the border color to text color, as it was before

### CODE REVIEW

**Comment by WickyNilliams** [comment]
Thanks for this!

**Comment by WickyNilliams** [comment]
Just realised this wasn't 100% backwards compatible. Whilst the default theme kept working, it would break people's existing custom themes (since this new variable is not defined in their theme).

I had to make this change to the picker's styles:

```diff
-border: 1px solid var(--duet-color-border);
+border: 1px solid var(--duet-color-border, var(--duet-color-text));
```

Now it will fallback to the old value, even for custom themes. Thankfully I hadn't released yet :)

**Comment by dmitriid** [comment]
Makes sense :)

**Comment by WickyNilliams** [comment]
Released in `v1.3.0`

**Pull request merged**
